### PR TITLE
remove hardcoded env variables for run handler

### PR DESCRIPTION
**Pull request by csantanapr**
This allows for a customized invoker with an SPI to send more variables in the run handler

### CODE REVIEW

**Comment by csantanapr** [comment]
@eweiter could you review this PR.

**Review by eweiter — APPROVED** [review]
LGTM

**Comment by eweiter** [comment]
@vvraskin ,@csantanapr Had asked me to review this, the logic looks clear and correct.  Please merge when you can.

**Review by vvraskin — APPROVED** [review]
LGTM

**Pull request merged**
